### ISSUE TITLE
Connect to Domoticz Synology

### ISSUE THREAD

**Issue by elcomes** [jjtbsomhorst/eu.jeroensomhorst.domoticz#1]
Ik probeer verbinding te maken met domoticz op mijn synology op poort 8084, maar ik krijg een time-out.

Timed out after 30000ms

**Comment by jjtbsomhorst** [comment]
Hallo,

Dat is raar. Ik zal er dit weekend naar kijken of ik kan achterhalen wat
daar mis gaat.

Weet je hoe je applicaties via cli moet draaien?

Op do 31 jan. 2019 21:00 schreef elcomes <notifications@github.com:

**Comment by elcomes** [comment]
Misschien is dat het probleem. Dat ik niet weet hoe het moet.
  

  
Maar zag in het dev gedeelte van Homey dat er volgens mij wel verbinding is.

**Comment by elcomes** [comment]
Ik ben er achter gekomen dat het komt omdat ook alle ongebruikte apparaten worden opgehaald.
  

  
En door rfxcom had ik er heel veel instaan.
  
Die had ik verwijderd en toen werkte het.
  

  
Misschien optie dat hij alleen gebruikte Domoticz apparaten ophaald.
  
  
  
  
  

  
  
  
  
  
  

  
  
>

**Comment by jjtbsomhorst** [comment]
De code in de Appstore doet dat nog inderdaad. Dat had ik al gefixt op GitHub. Ik zal de app maar weer eens updaten :)
