### ISSUE TITLE
P1 issue

### ISSUE THREAD

**Issue by Michel58** [jjtbsomhorst/eu.jeroensomhorst.domoticz#13]
Hi, for a while know im trying to get my P1 smart meter data from my Domoticz (on raspberry) to my Homey. Except for gas, which updated once, i get no values at all. Hue lights i can turn on and off so there is a good connection. Do you have any idea? Btw the smartmeter is the newest version 5

**Comment by jjtbsomhorst** [comment]
Does the smart meter have correct values inside domoticz? Can you post the output from 
http://<domoticshost>:<domoticsport>/json.htm?type=devices
