### ISSUE TITLE
timeouts

### ISSUE THREAD

**Issue by satbopper** [jjtbsomhorst/eu.jeroensomhorst.domoticz#2]
The app works here in combination with a cam but in the homey v2 app i get a lot of timeout errors
those red popups on top of the screen
then in my case if you turn the device on in the homey app,i can see on the domoticz page that the device is turned on,in the homey app if you you stay on the screen to turn on the device you will see that the device is on because the color is orange,if you in the homey app go to for example your flows and come back to the device you just turned on,the color is black as if it is turned off

**Comment by jjtbsomhorst** [comment]
Could you go to the settings page and in the log view give an example of what it states? This can be done either by making a screenshot for isntance. 

Or if you know how to use the athom cli tools could you run the app using cli and give me an example of the data returned by the app when a timeout occurs?

**Comment by jjtbsomhorst** [comment]
@satbopper can you help me out here? Without further explanation I can't reproduce / find out what is going

**Comment by satbopper** [comment]
ok i will produce some info and come back to you

**Comment by jjtbsomhorst** [comment]
@satbopper  any update?
