### ISSUE TITLE
Do we have to use login?

### ISSUE THREAD

**Issue by eddiex666** [jjtbsomhorst/eu.jeroensomhorst.domoticz#3]
Nice app..

In domoticz i have excluded local nett login.
The app is not working/fetching any info from domoticz.

The app require username and pw.

Do we need to force login on domoticz web portal?

**Comment by jjtbsomhorst** [comment]
That is indeed the way how I build it. Can you tell me where in domoticz you can disable login? So i can test it locally. 

I'm not a domoticz expert ;)

**Comment by eddiex666** [comment]
Under settings (Main page) / system

Local Networks (no username/password):

Add your network...(example)
192.168.1.*

And the Homey is on the same network

:+)

**Comment by eddiex666** [comment]
I have'nt got ut working yeat. But i Hope the app Will work soon.

For now i did a global notification in domoticz.
To send to the Homey webhook.
The webhook can receive data1 data2 etc http post.
So then i Add a notification string on the device i would like to send to Homey.

The good is that i now have a global sender and receiver.

The bad is that i have to Add notification string to all device i would like to send to Homey.
And i must Add a receiver om Homey for every receiving events.

**Comment by jjtbsomhorst** [comment]
I already see a possible bug. When you add a device and you leave the username/password blank and hit the save button you get a message 'please fill in all fields'.  This way you can't continue. A possible work around, for now, is to fill in some dummy data on the username/password. Hit the save button. It should then just find everything that is connected. 

If not.. cancel pairing go to apps -> Domoticz -> configure app -> remove the username/password and hit save. Next restart the app and you should be able to discover devices.

p.s. from a personal standpoint I think its a bad idea to not have a username/password. ;)

**Comment by eddiex666** [comment]
Hmmm.
I tryed that and get
Ether 
No device
Or
Error connect

I have re-installed 
Both 0.6 and 0.7
Added and remove server and username.

What versjon og domoticz Are you testing on?

**Comment by jjtbsomhorst** [comment]
Version: 4.9700
Build Hash: a3a45906

Could you check in the settings screen if you hit refresh what it shows in the log? Also if the settings saved are stored correctly? Just to be sure

p.s. can you check what you get when you go to <yourdomoticzurl>/json.htm?type=devices

**Comment by eddiex666** [comment]
Version: 4.9796
Build Hash: 4952b51e
Compile Date: 2018-07-26 17:01:10
dzVents Version: 2.4.7
Python Version: None



I get this (and more)..
{
   "ActTime" : 1549193098,
   "AstrTwilightEnd" : "19:00",
   "AstrTwilightStart" : "05:60",
   "CivTwilightEnd" : "17:21",
   "CivTwilightStart" : "07:39",
   "DayLength" : "08:10",
   "NautTwilightEnd" : "18:12",
   "NautTwilightStart" : "06:48",
   "ServerTime" : "2019-02-03 12:24:58",
   "SunAtSouth" : "12:05",
   "Sunrise" : "08:25",
   "Sunset" : "16:35",
   "app_version" : "4.9796",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "20.9 C, 45 %",
         "Description" : "",
         "DewPoint" : "8.52",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : true,
         "Humidity" : 45,
         "HumidityStatus" : "Comfortable",
         "ID" : "A401",
         "LastUpdate" : "2017-06-07 17:57:55",
         "Name" : "Unknown",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "SubType" : "Rubicson/IW008T/TX95",
         "Temp" : 20.899999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 0,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },

**Comment by jjtbsomhorst** [comment]
Could you post me the complete output? OR tell met he max idx value you see? I just updated the repository. Can you install this version using cli? I still would like to see the complete output ;)

**Comment by eddiex666** [comment]
its huge :-)


[domoticz-devices.zip](https://github.com/jjtbsomhorst/eu.jeroensomhorst.domoticz/files/2825668/domoticz-devices.zip)

**Comment by jjtbsomhorst** [comment]
I think we found the problem here. I just looked at the file and I see around 6000 devices that are not used. I have seen this before in a rfxcom environment. Could you try again with the current version that is on Github? I did some digging and now it (the app) should only get the used devices. And be aware you need to use the beta branch. 

If this doesn't work I'm wondering how long it takes to load that url we talked about previously in a browser

**Comment by eddiex666** [comment]
Hi...
Ok. I think idx can be vert high.
I have'nt seen any Max values on domoticz doc.
Yes i have a lot of devices...
I also use domoticz as a source for 2 other rfx systems :-) (they update my domoticz virtual devices.

I am not good at manually update om Homey yeat.
How do i do that?
I did get cli-athom om the Mac Rynning :-)
I would love to know how to code om Homey :-)

Nice work, Edward
Python and php dude.

**Comment by eddiex666** [comment]
ok, after short youtube.. i installed the BETA from github.
this is working.
i was able to get 5 devices in the device list.

**Comment by eddiex666** [comment]
if possible it would be brilliant to get devices like "Electric" and some more sensors.
the type is "Usage" and maybe "Security" if possible :-) 

the cool thing is that with domotica and pythin/php i can read allmost everything down from the "smarthouse" stuff, and store data inside Domoticz...
for example: read data from web api and pipe it into domoticz
then read it inside Homey.

Does the app pull? how ofen?

**Comment by jjtbsomhorst** [comment]
> if possible it would be brilliant to get devices like "Electric" and some more sensors.
> the type is "Usage" and maybe "Security" if possible :-)

How do you mean? Currently you get the list of devices that can be found. They have capabilities based on the types specified in Domoticz. 

> Does the app pull? how ofen?

The app pulls data from domotics every second. But only if there are devices paired.

**Comment by eddiex666** [comment]
Strange, i can only see temp sensors.
Devices in side domotics that are marked temp.
i can see both hardware based and virtual sensors that are temp

type = temp

i testing the 0.1.0 version, is this the one you wanted me to test?

**Comment by jjtbsomhorst** [comment]
I just found out what is going wrong. It's the 2.0 app. For some reason it only shows certain amount of devices. I'm closing this bug for now since you can retrieve devices. I will make a new bug for retrieving all devices.

**Comment by jjtbsomhorst** [comment]
Closed. Was fixed in 0.1.0
