### ISSUE TITLE
P1 showing 2 devices of 8 and showing zero data

### ISSUE THREAD

**Issue by vvhillo** [jjtbsomhorst/eu.jeroensomhorst.domoticz#6]
I added your app and it recognized two devices of 8 but the 2 devices that where added show no data at all. Please see the log attached from your app and the json I see when I use the API of Domoticz.

[domoticz app log.txt](https://github.com/jjtbsomhorst/eu.jeroensomhorst.domoticz/files/2904704/domoticz.app.log.txt)

[domoticz_devices.txt](https://github.com/jjtbsomhorst/eu.jeroensomhorst.domoticz/files/2904696/domoticz_devices.txt)

**Comment by jjtbsomhorst** [comment]
could you try to restart the app? Als which devices from the list have you added to Homey?

**Comment by jjtbsomhorst** [comment]
Can you please help me out here. Which devices do you see and which did you expect? 

I made some changes and in the beta branch most of the devices should be available now?
