### ISSUE TITLE
Weather station data = Thermostat in Homey

### ISSUE THREAD

**Issue by k4mrat** [jjtbsomhorst/eu.jeroensomhorst.domoticz#7]
Hi! Great app, just what I’ve been looking for after getting a lot of grey hairs with trying to get Domoticz to work over MQTT to Homey. 

But, it seems as certain weather data is reported to Homey as simply temp or humidity, while others are reported as Thermostats with the ability to change target temp etc. Is this a God-mode for changing the weather, is it a setting in Domo or a problem with the app/Homey? :)

**Comment by jjtbsomhorst** [comment]
I tried to add some god mode at first but the gods didn't premit me doing so. The reason for this is that I   add the on/off functionality by default to any device I find that should be having this capability. Can you tell me which device you would have expect to have this on/of and which you don't expect? Because domotic devices can be such a chaos it's hard to map the correct capability to the devices.

**Comment by k4mrat** [comment]
Haha, cranky Gods!!
Totally understandable, it’s a bit messy. 
What I can see right now: 
I get a Tunex station with WTGR800 sensor as Thermostat. 
A Xiron also with WTGR800 as a Thermostat. 
And one that comes in as FineOffset, also WTGR800, that actually kills the Homey app completely with a white screen and I need to reboot the Homey app. 
One that comes in as Alecto V5 uses a LaCrosseTX3 sensor and that works perfectly as a weather station, not thermostat!

**Comment by jjtbsomhorst** [comment]
Are you able to send me the json that is found at the following url: 

http(s)://<domoticz ip>/json.htm?type=devices&used=true
Maybe I can find a way to distinguish if it's supposed to be a thermostat or 'just'  the weather.

**Comment by k4mrat** [comment]
Well, I do find a bunch of stuff there. A list a mile long... not sure it’s what you’re looking for. Found at [ipadress]/json.htm?type=devices&used=true...
Is that what you’re looking for?
Otherwise I’m afraid you’re gonna have to hit me up on my email and talk to me like in five :D
b.kallin@gmail.com

**Comment by jjtbsomhorst** [comment]
yes that is what I'm looking for. What you could do is download that file and add it to the comments. (drag and drop into the comment box should work).

**Comment by k4mrat** [comment]
No access to computer for a while, I’ll try over phone and hope it works! May well just be a txt...
[Domoticz.json.txt](https://github.com/jjtbsomhorst/eu.jeroensomhorst.domoticz/files/2977890/Domoticz.json.txt)

**Comment by jjtbsomhorst** [comment]
no problemo

**Comment by k4mrat** [comment]
Think i've solved the problem. No idea how to work with pull requests and stuff though =D

**Comment by jjtbsomhorst** [comment]
can i close this then?

**Comment by k4mrat** [comment]
yeah, think so! 
Did some changes in the code, you want them?

**Comment by jjtbsomhorst** [comment]
yeah send me a pull request.

**Comment by jjtbsomhorst** [comment]
I have merged your changes in the beta branch.
