### ISSUE TITLE
After configuring once, im not able to configure extra devices, after reinstalling it skips all the devices, saying "no Devices configured yet"

### ISSUE THREAD

**Issue by Fadoz** [jjtbsomhorst/eu.jeroensomhorst.domoticz#8]

**Comment by Fadoz** [comment]
im not able to use the app at all anymore, any suggestions?

2019-3-28 18:50:25: No devices configured yet. Skip
2019-3-28 18:50:25: Retrieve devices
2019-3-28 18:50:24: No devices configured yet. Skip
2019-3-28 18:50:24: Retrieve devices
2019-3-28 18:50:23: No devices configured yet. Skip
2019-3-28 18:50:23: Retrieve devices
2019-3-28 18:50:22: No devices configured yet. Skip
2019-3-28 18:50:22: Retrieve devices
2019-3-28 18:50:21: No devices configured yet. Skip
2019-3-28 18:50:21: Retrieve devices
2019-3-28 18:50:20: No devices configured yet. Skip
2019-3-28 18:50:20: Retrieve devices
2019-3-28 18:50:19: No devices configured yet. Skip
2019-3-28 18:50:19: Retrieve devices
2019-3-28 18:50:18: No devices configured yet. Skip
2019-3-28 18:50:18: Retrieve devices
2019-3-28 18:50:17: No devices configured yet. Skip
2019-3-28 18:50:17: Retrieve devices
2019-3-28 18:50:16: No devices configured yet. Skip
2019-3-28 18:50:16: Retrieve devices
2019-3-28 18:50:15: No devices configured yet. Skip
2019-3-28 18:50:15: Retrieve devices
2019-3-28 18:50:14: No devices configured yet. Skip
2019-3-28 18:50:14: Retrieve devices
2019-3-28 18:50:13: No devices configured yet. Skip
2019-3-28 18:50:13: Retrieve devices
2019-3-28 18:50:12: No devices configured yet. Skip
2019-3-28 18:50:12: Retrieve devices
2019-3-28 18:50:11: No devices configured yet. Skip
2019-3-28 18:50:11: Retrieve devices
2019-3-28 18:50:10: No devices configured yet. Skip
2019-3-28 18:50:09: Retrieve devices
2019-3-28 18:50:08: No devices configured yet. Skip
2019-3-28 18:50:08: Retrieve devices
2019-3-28 18:50:07: No devices configured yet. Skip
2019-3-28 18:50:07: Retrieve devices
2019-3-28 18:50:06: No devices configured yet. Skip
2019-3-28 18:50:06: Retrieve devices
2019-3-28 18:50:05: No devices configured yet. Skip
2019-3-28 18:50:05: Retrieve devices
2019-3-28 18:50:04: No devices configured yet. Skip
2019-3-28 18:50:04: Retrieve devices
2019-3-28 18:50:03: No devices configured yet. Skip
2019-3-28 18:50:03: Retrieve devices
2019-3-28 18:50:02: No devices configured yet. Skip
2019-3-28 18:50:02: Retrieve devices
2019-3-28 18:50:01: No devices configured yet. Skip
2019-3-28 18:50:01: Retrieve devices
2019-3-28 18:50:00: No devices configured yet. Skip
2019-3-28 18:50:00: Retrieve devices

**Comment by jjtbsomhorst** [comment]
what happens if you try to pair new devices? What do you see in the log? Are you able to install it using cli / github and tell me what the logs say when you want to pair?

**Comment by Fadoz** [comment]
Hi Jeroen,

I'm quite new to Homey, so I don't really understand what you mean by using the CLI, does Homey have a cli?

in the app im not seeing any devices. before there where but I wanted to add some other devices from Domoticz. I was unable to configure other devices (or couldn't found a button to do so) so I tried reinstalling the Domoticz app, I was hoping that de configure menu that I had previously would appear again. but it just doesn't 

attached a screenshot of what im seeing in my Domoticz app:
![PNG-afbeelding](https://user-images.githubusercontent.com/49023536/55185408-90ed6f00-5194-11e9-9476-450eb424a57c.png)
![PNG-afbeelding 2](https://user-images.githubusercontent.com/49023536/55185579-ef1a5200-5194-11e9-809a-a4a80fdfe4a4.png)

**Comment by jjtbsomhorst** [comment]
Hi,

Ik zie aan de interface dat je Nederlands kunt. Klopt dat? Je kunt een
nieuw device toevoegen via apparaten en dan her plusje rechts boven in. Als
je dat doet en kiest voor domoticz wat gebeurt er dan ?

De configuratie waar je het over hebt is toch het screenshot van hieronder

**Comment by Fadoz** [comment]
Hi, 

Klopt ja, Nederlands moet lukken... basis dingen in Homey nog niet echt, mijn excuus want het werkt gewoon. ik ga deze maar gauw sluiten zeg... over jezelf dom voelen gesproken... ;-)

Ik denk dat ik de eerste keer de app heb geïnstalleerd en daarna de 'devices' heb toegevoegd (en dus niets in de app config heb gedaan), terwijl ik hiervoor via de apps-->Domoticz-->configure app probeerde om de apparaten erin te krijgen.

alsnog heel erg bedankt voor de hulp.

**Comment by jtebbens** [comment]
Issues seems back. Using the beta version v0.1.4 and after adding once. You can't seem to add new devices in a second attempt.
